
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rfjolkadxfixxagpidws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_0hhJclSJdUdu25v1GVRN4Q_Qlp7Od57";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
